<div class="form-group row">
    <?php echo $this->formLabel($form->get('surName')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formText($form->get('surName')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('surName')); ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('lastNamePrefix')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formText($form->get('lastNamePrefix')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('lastNamePrefix')); ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('lastName')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formText($form->get('lastName')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('lastName')); ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('screenName')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formText($form->get('screenName')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('screenName')); ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('club')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formSelect($form->get('club')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('club')); ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('user')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formSelect($form->get('user')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('user')); ?>
    </div>
</div>
