<?php
if (empty($image) || $image->getImageId() === null) {
    echo $this->partial('upload-images/partial/upload_image.phtml', array('formImage' => $formImage));
} else {
    ?>
    <div class="col-lg-12 col-md-12 col-sm-12">
        <hr/>
        <div id="image<?php echo $image->getImageId(); ?>">
            <?php echo '<img class="img-thumbnail img-responsive " src="/' . $image->getImageTypes('400x400')[0]->getFolder() . $image->getImageTypes('400x400')[0]->getFileName() . '?v=' . rand() . '" alt="' . $image->getAlt() . '"/>'; ?>
            <div class="imageOptions">
                <span data-imageid="<?php echo $image->getImageId(); ?>" class="btn btn-dark btn-sm editImage" data-dismiss="modal" data-target="#showImages"><i class="fas fa-edit"></i></span>
                <span data-imageid="<?php echo $image->getImageId(); ?>" class="btn btn-dark btn-sm deleteImageObject"><i class="fas fa-trash-alt"></i></span>
                <span data-id="<?php echo $returnURL['id'] ?>" data-route="<?php echo $returnURL['route'] ?>" data-action="<?php echo $returnURL['action'] ?>" data-imageid="<?php echo $image->getImageId(); ?>" class="btn btn-dark btn-sm recropImage"><i class="fa fa-crop" aria-hidden="true"></i></span>
            </div>
        </div>
        <hr/>
    </div>
    <!-- Edit afbeelding -->
    <?php echo $this->partial('upload-images/partial/edit_image.phtml'); ?>
    <?php
}
?>
