<?php

namespace DoctrineORMModule\Proxy\__CG__\Result\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HomeGameResult extends \Result\Entity\HomeGameResult implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'id', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'goalsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'pointsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'shotOnTargetH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'totalShotsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'foulsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'possessionH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'cornersH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'tacklesH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'yellowCardsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'redCardsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'injuriesH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'shotAccuracyH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'passAccuracyH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'player'];
        }

        return ['__isInitialized__', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'id', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'goalsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'pointsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'shotOnTargetH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'totalShotsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'foulsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'possessionH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'cornersH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'tacklesH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'yellowCardsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'redCardsH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'injuriesH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'shotAccuracyH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'passAccuracyH', '' . "\0" . 'Result\\Entity\\HomeGameResult' . "\0" . 'player'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HomeGameResult $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGoalsH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoalsH', []);

        return parent::getGoalsH();
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsH', []);

        return parent::getPointsH();
    }

    /**
     * {@inheritDoc}
     */
    public function getShotOnTargetH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShotOnTargetH', []);

        return parent::getShotOnTargetH();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalShotsH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalShotsH', []);

        return parent::getTotalShotsH();
    }

    /**
     * {@inheritDoc}
     */
    public function getFoulsH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoulsH', []);

        return parent::getFoulsH();
    }

    /**
     * {@inheritDoc}
     */
    public function getPossessionH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPossessionH', []);

        return parent::getPossessionH();
    }

    /**
     * {@inheritDoc}
     */
    public function getCornersH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCornersH', []);

        return parent::getCornersH();
    }

    /**
     * {@inheritDoc}
     */
    public function getTacklesH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTacklesH', []);

        return parent::getTacklesH();
    }

    /**
     * {@inheritDoc}
     */
    public function getYellowCardsH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYellowCardsH', []);

        return parent::getYellowCardsH();
    }

    /**
     * {@inheritDoc}
     */
    public function getRedCardsH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedCardsH', []);

        return parent::getRedCardsH();
    }

    /**
     * {@inheritDoc}
     */
    public function getInjuriesH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInjuriesH', []);

        return parent::getInjuriesH();
    }

    /**
     * {@inheritDoc}
     */
    public function getShotAccuracyH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShotAccuracyH', []);

        return parent::getShotAccuracyH();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassAccuracyH()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassAccuracyH', []);

        return parent::getPassAccuracyH();
    }

    /**
     * {@inheritDoc}
     */
    public function getGame()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGame', []);

        return parent::getGame();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlayer', []);

        return parent::getPlayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setGoalsH($goalsH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoalsH', [$goalsH]);

        return parent::setGoalsH($goalsH);
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsH($pointsH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsH', [$pointsH]);

        return parent::setPointsH($pointsH);
    }

    /**
     * {@inheritDoc}
     */
    public function setShotOnTargetH($shotOnTargetH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShotOnTargetH', [$shotOnTargetH]);

        return parent::setShotOnTargetH($shotOnTargetH);
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalShotsH($totalShotsH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalShotsH', [$totalShotsH]);

        return parent::setTotalShotsH($totalShotsH);
    }

    /**
     * {@inheritDoc}
     */
    public function setFoulsH($foulsH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoulsH', [$foulsH]);

        return parent::setFoulsH($foulsH);
    }

    /**
     * {@inheritDoc}
     */
    public function setPossessionH($possessionH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPossessionH', [$possessionH]);

        return parent::setPossessionH($possessionH);
    }

    /**
     * {@inheritDoc}
     */
    public function setCornersH($cornersH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCornersH', [$cornersH]);

        return parent::setCornersH($cornersH);
    }

    /**
     * {@inheritDoc}
     */
    public function setTacklesH($tacklesH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTacklesH', [$tacklesH]);

        return parent::setTacklesH($tacklesH);
    }

    /**
     * {@inheritDoc}
     */
    public function setYellowCardsH($yellowCardsH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYellowCardsH', [$yellowCardsH]);

        return parent::setYellowCardsH($yellowCardsH);
    }

    /**
     * {@inheritDoc}
     */
    public function setRedCardsH($redCardsH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRedCardsH', [$redCardsH]);

        return parent::setRedCardsH($redCardsH);
    }

    /**
     * {@inheritDoc}
     */
    public function setInjuriesH($injuriesH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInjuriesH', [$injuriesH]);

        return parent::setInjuriesH($injuriesH);
    }

    /**
     * {@inheritDoc}
     */
    public function setShotAccuracyH($shotAccuracyH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShotAccuracyH', [$shotAccuracyH]);

        return parent::setShotAccuracyH($shotAccuracyH);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassAccuracyH($passAccuracyH)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassAccuracyH', [$passAccuracyH]);

        return parent::setPassAccuracyH($passAccuracyH);
    }

    /**
     * {@inheritDoc}
     */
    public function setGame($game)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGame', [$game]);

        return parent::setGame($game);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlayer($player)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlayer', [$player]);

        return parent::setPlayer($player);
    }

}
