<?php

namespace DoctrineORMModule\Proxy\__CG__\Result\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AwayGameResult extends \Result\Entity\AwayGameResult implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'id', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'goalsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'pointsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'shotOnTargetA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'totalShotsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'foulsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'possessionA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'cornersA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'tacklesA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'yellowCardsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'redCardsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'injuriesA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'shotAccuracyA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'passAccuracyA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'player'];
        }

        return ['__isInitialized__', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'id', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'goalsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'pointsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'shotOnTargetA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'totalShotsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'foulsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'possessionA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'cornersA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'tacklesA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'yellowCardsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'redCardsA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'injuriesA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'shotAccuracyA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'passAccuracyA', '' . "\0" . 'Result\\Entity\\AwayGameResult' . "\0" . 'player'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AwayGameResult $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGoalsA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoalsA', []);

        return parent::getGoalsA();
    }

    /**
     * {@inheritDoc}
     */
    public function getPointsA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointsA', []);

        return parent::getPointsA();
    }

    /**
     * {@inheritDoc}
     */
    public function getShotOnTargetA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShotOnTargetA', []);

        return parent::getShotOnTargetA();
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalShotsA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalShotsA', []);

        return parent::getTotalShotsA();
    }

    /**
     * {@inheritDoc}
     */
    public function getFoulsA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoulsA', []);

        return parent::getFoulsA();
    }

    /**
     * {@inheritDoc}
     */
    public function getPossessionA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPossessionA', []);

        return parent::getPossessionA();
    }

    /**
     * {@inheritDoc}
     */
    public function getCornersA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCornersA', []);

        return parent::getCornersA();
    }

    /**
     * {@inheritDoc}
     */
    public function getTacklesA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTacklesA', []);

        return parent::getTacklesA();
    }

    /**
     * {@inheritDoc}
     */
    public function getYellowCardsA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getYellowCardsA', []);

        return parent::getYellowCardsA();
    }

    /**
     * {@inheritDoc}
     */
    public function getRedCardsA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRedCardsA', []);

        return parent::getRedCardsA();
    }

    /**
     * {@inheritDoc}
     */
    public function getInjuriesA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInjuriesA', []);

        return parent::getInjuriesA();
    }

    /**
     * {@inheritDoc}
     */
    public function getShotAccuracyA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShotAccuracyA', []);

        return parent::getShotAccuracyA();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassAccuracyA()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassAccuracyA', []);

        return parent::getPassAccuracyA();
    }

    /**
     * {@inheritDoc}
     */
    public function getGame()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGame', []);

        return parent::getGame();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlayer', []);

        return parent::getPlayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setGoalsA($goalsA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoalsA', [$goalsA]);

        return parent::setGoalsA($goalsA);
    }

    /**
     * {@inheritDoc}
     */
    public function setPointsA($pointsA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointsA', [$pointsA]);

        return parent::setPointsA($pointsA);
    }

    /**
     * {@inheritDoc}
     */
    public function setShotOnTargetA($shotOnTargetA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShotOnTargetA', [$shotOnTargetA]);

        return parent::setShotOnTargetA($shotOnTargetA);
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalShotsA($totalShotsA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalShotsA', [$totalShotsA]);

        return parent::setTotalShotsA($totalShotsA);
    }

    /**
     * {@inheritDoc}
     */
    public function setFoulsA($foulsA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoulsA', [$foulsA]);

        return parent::setFoulsA($foulsA);
    }

    /**
     * {@inheritDoc}
     */
    public function setPossessionA($possessionA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPossessionA', [$possessionA]);

        return parent::setPossessionA($possessionA);
    }

    /**
     * {@inheritDoc}
     */
    public function setCornersA($cornersA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCornersA', [$cornersA]);

        return parent::setCornersA($cornersA);
    }

    /**
     * {@inheritDoc}
     */
    public function setTacklesA($tacklesA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTacklesA', [$tacklesA]);

        return parent::setTacklesA($tacklesA);
    }

    /**
     * {@inheritDoc}
     */
    public function setYellowCardsA($yellowCardsA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setYellowCardsA', [$yellowCardsA]);

        return parent::setYellowCardsA($yellowCardsA);
    }

    /**
     * {@inheritDoc}
     */
    public function setRedCardsA($redCardsA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRedCardsA', [$redCardsA]);

        return parent::setRedCardsA($redCardsA);
    }

    /**
     * {@inheritDoc}
     */
    public function setInjuriesA($injuriesA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInjuriesA', [$injuriesA]);

        return parent::setInjuriesA($injuriesA);
    }

    /**
     * {@inheritDoc}
     */
    public function setShotAccuracyA($shotAccuracyA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShotAccuracyA', [$shotAccuracyA]);

        return parent::setShotAccuracyA($shotAccuracyA);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassAccuracyA($passAccuracyA)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassAccuracyA', [$passAccuracyA]);

        return parent::setPassAccuracyA($passAccuracyA);
    }

    /**
     * {@inheritDoc}
     */
    public function setGame($game)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGame', [$game]);

        return parent::setGame($game);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlayer($player)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlayer', [$player]);

        return parent::setPlayer($player);
    }

}
