<?php
$this->headTitle($this->translator()->translate('season.title'));

$this->mainMenu()->setActiveItemId($this->translator()->translate('season.active.item'));

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('season.manage') => $this->url('seasons'),
    $this->translator()->translate('season.add') => $this->url('seasons', ['action' => 'show'])
]);
?>
<div class="row">
    <h1 class="col"><?php echo $season->getName(); ?></h1>
</div>
<div class="row mb-1">
    <div class="col"><?php echo $season->getStartDate()->format('d-m-Y');  ?>&nbsp;-&nbsp;<?php echo $season->getEndDate()->format('d-m-Y');  ?></div>
</div>
<div class="row mt-3">
    <label class="col">
        <?php echo $this->translator()->translate('season.lock.game.schedule'); ?>&nbsp;<?php echo ($season->getLockPlaySchedule() == 0 ? '<i class="far fa-check-circle text-success"></i>' : '<i class="far fa-times-circle text-danger"></i>'); ?>
    </label>
</div>
<div class="row">
    <h3 class="col"><?php echo $this->translator()->translate('season.competition.title'); ?></h3>
    <div class="col-md-auto">
        <a href="<?php echo $this->url('seasons'); ?>" class="btn btn-danger"
           title="<?php echo $this->translator()->translate('cancel') ?>"><?php echo $this->translator()->translate('cancel') ?></a>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        <table class="table table-sm table-bordered table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col" class="text-center"><?php echo $this->translator()->translate('season.game.number'); ?></th>
                    <th scope="col"><?php echo $this->translator()->translate('season.game.home.player.title'); ?></th>
                    <th scope="col"><?php echo $this->translator()->translate('season.game.away.player.title'); ?></th>
                    <th scope="col"><?php echo $this->translator()->translate('season.game.playdate'); ?></th>
                    <th scope="col" class="text-center"><i class="fas fa-cogs"></i></th>
                    <th scope="col"><?php echo $this->translator()->translate('season.game.competition'); ?></th>
                </tr>
            </thead>
            <tbody <?php echo ($season->getLockPlaySchedule() != 1? 'id="sortable"':''); ?>>
                <?php foreach ($games as $game) { ?>
                    <tr id="gameId<?php echo $game->getId(); ?>" data-gameid="<?php echo $game->getId(); ?>" class="ui-state-default">
                        <td scope="row" class="text-center"><?php echo $game->getSortOrder(); ?></td>
                        <td><?php echo $game->getHomePlayer()->getFullName(); ?></td>
                        <td><?php echo $game->getAwayPlayer()->getFullName(); ?></td>
                        <td id="gamePlayDate" class="text-center"><?php echo (is_object($game->getPlayDate()) ? $game->getPlayDate()->format('d-m-Y') : ''); ?></td>
                        <td class="text-center"><button type="button" data-gameid="<?php echo $game->getId(); ?>" class="btn btn-warning btn-sm setGameId" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-calendar-alt"></i></button></td>
                        <td><?php echo $game->getCompetition()->getName(); ?></td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><?php echo $this->translator()->translate('game.playdate'); ?></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <label class="form-label"><?php echo $this->translator()->translate('game.playdate'); ?></label>
                <input type="text" name="playDate" value="" id="playDate" class="form-control datepicker" autocomplete="off" />
                <input type="hidden" name="gameId" value="" id="gameId" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-dark setPlayDate"><?php echo $this->translator()->translate('save'); ?></button>
                <button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo $this->translator()->translate('cancel'); ?></button>
            </div>
        </div>
    </div>
</div>
<style>
    .ui-sortable-helper td {
        width:20% !important;
        min-width: 20% !important;
    }
</style>
<script>
    $(function () {
        $("#sortable").sortable({
            helper: fixHelper,
            update: function (event, ui) {
                var gameSortOrders = [];
                $(this).children().each(function (index) {
                    var sortOrder = index + 1;
                    var gameId = $(this).data('gameid');
                    gameSortOrders[sortOrder] = gameId
                    $(this).find('td').first().html(index + 1);
                });

                $.ajax({
                    type: 'POST',
                    data: {
                        gameSortOrders: gameSortOrders
                    },
                    url: "<?= $this->url('gameajax', ['action' => 'setSortOrder']); ?>",
                    async: true,
                    success: function (data) {
                        if (data.success === true) {
                        } else {
                        }
                    }
                });

            }
        });
        $("#sortable").disableSelection();


        // Return a helper with preserved width of cells  
        var fixHelper = function (e, tr)
        {
            var $originals = tr.children();
            var $helper = tr.clone();
            $helper.children().each(function (index)
            {
                // Set helper cell sizes to match the original sizes
                $(this).width($originals.eq(index).width());
            });
            return tr;
        }
    });



    /**
     * Set the game id into the hidden input field of the model
     */
    $(".setGameId").on("click", function () {
        var gameId = $(this).data('gameid');
        $('input#gameId').val(gameId);
    });

    /**
     * Set the play date for the game
     */
    $(".setPlayDate").on("click", function () {
        console.log('test');
        var gameId = $('#gameId').val();
        var playDate = $('#playDate').val();
        $.ajax({
            type: 'POST',
            data: {
                gameId: gameId,
                playDate: playDate
            },
            url: "<?= $this->url('gameajax', ['action' => 'setPlayDate']); ?>",
            async: true,
            success: function (data) {
                if (data.success === true) {
                    $('tr#gameId' + gameId).children('td#gamePlayDate').html(playDate);
                    $('#exampleModal').modal('toggle');
                } else {
                }
            }
        });
    });

</script>