<?php
$this->headTitle($this->translator()->translate('season.playoff.title'));

$this->mainMenu()->setActiveItemId($this->translator()->translate('season.active.item'));

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('season.manage') => $this->url('seasons'),
    $this->translator()->translate('season.playoffs') => $this->url('seasons', ['action' => 'play-offs'])
]);
?>
<div class="row">
    <h1 class="col"><?php echo $season->getName(); ?></h1>
</div>
<div class="row">
    <h3 class="col"><?php echo $this->translator()->translate('season.playoff.title'); ?></h3>
    <div class="col-md-auto">
        <a href="<?php echo $this->url('seasons'); ?>" class="btn btn-danger"
           title="<?php echo $this->translator()->translate('cancel') ?>"><?php echo $this->translator()->translate('cancel') ?></a>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        <button id="addPlayOff" class="btn btn-sm btn-dark" data-season-id="<?php echo $season->getId(); ?>">
            <i class="fas fa-plus-square"></i>
            <?php echo $this->translator()->translate('season.add.playoffs'); ?>
        </button>
    </div>
</div>


<script>
    $('button#addPlayOff').on("click", function () {
        var seasonId = $(this).data('season-id');
        console.log(seasonId);
        $.ajax({
            type: 'POST',
            data: {
                seasonId: seasonId
            },
            url: "<?= $this->url('playoffajax', ['action' => 'add']); ?>",
            async: true,
            success: function (data) {
                if (data.succes === true) {
                } else {
                }
            }
        });

    });
</script>