<?php
$this->headTitle($this->translator()->translate('season.playoff.title'));

$this->mainMenu()->setActiveItemId($this->translator()->translate('season.active.item'));

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('season.manage') => $this->url('seasons'),
    $this->translator()->translate('season.playoffs') => $this->url('seasons', ['action' => 'play-offs'])
]);
?>
<div class="row">
    <h1 class="col"><?php echo $season->getName(); ?></h1>
</div>
<div class="row">
    <h3 class="col"><?php echo $this->translator()->translate('season.playoff.title'); ?></h3>
    <div class="col-md-auto">
        <a href="<?php echo $this->url('seasons'); ?>" class="btn btn-danger"
           title="<?php echo $this->translator()->translate('cancel') ?>"><?php echo $this->translator()->translate('cancel') ?></a>
    </div>
</div>
<div class="row mt-3">
    <div class="col-md-auto">
        <button id="addPlayOff" class="btn btn-dark mb-2 w-100" data-season-id="<?php echo $season->getId(); ?>">
            <i class="fas fa-plus-square"></i>
            <?php echo $this->translator()->translate('season.add.playoffs'); ?>
        </button>
        <select name="playOffType" class="form-control">
            <option value="0">--Maak een keuze--</option>
            <option value="1">Promotie</option>
            <option value="2">Degredatie</option>
            <option value="3">Kampioenschap</option>
        </select>
    </div>
</div>
<div class="row mt-3">
    <dv class="col">
        <table id="playOffTable" class="table table-sm table-bordered">
            <thead class="thead-dark">
            <tr>
                <th><?php echo $this->translator()->translate('playoff.table.name') ?></th>
                <th class="text-center"><i class="fas fa-cogs"></i></th>
            </tr>
            </thead>
            <tbody>

            </tbody>
        </table>
    </dv>
</div>


<script>
    $('button#addPlayOff').on("click", function () {
        var seasonId = $(this).data('season-id');
        var playOffTypeId = $('select[name=playOffType]').val();

        if (seasonId != '' && playOffTypeId > 0) {

            $.ajax({
                type: 'POST',
                data: {
                    seasonId: seasonId,
                    playOffTypeId: playOffTypeId
                },
                url: "<?= $this->url('playoffajax', ['action' => 'add']); ?>",
                async: true,
                success: function (data) {
                    if (data.success === true) {
                        $('select[name=playOffType]').val(0)
                        var row = '<tr>';
                        row += '<td>' + data.playOff.name + '</td>';
                        row += '<td class="text-center"><button class="btn btn-dark playOffDetail" data-playoff="' + data.playOff.id + '" ><i class="fas fa-sliders-h"></i></button></td>';
                        row += '</tr>';
                        $('table#playOffTable').append(row);
                    } else {
                        bootbox.dialog({
                            message: '<p class="text-center mt-3 text-danger custom-font"><i class="fas fa-exclamation-triangle"></i> Er is iets mis gegaan. Probeer het nogmaals!</p>',
                        });
                    }
                }
            });
        } else {
            bootbox.dialog({
                message: '<p class="text-center mt-3 text-danger custom-font"><i class="fas fa-exclamation-triangle"></i> Selecteer een PlayOff type</p>',
            });
        }

    });
</script>