<?php echo $this->form()->openTag($form); ?>
<div class="row mb-3 pb-2 pt-2 justify-content-md-center border-bottom border-top">
    <div class="col col-lg-2"><h4><?php echo $game->getHomePlayer()->getFullName(); ?></h4></div>
    <div class="col-md-auto text-center"><h4><i class="far fa-futbol"></i></h4></div>
    <div class="col col-lg-2 text-right"><h4><?php echo $game->getAwayPlayer()->getFullName(); ?></h4></div>
</div>
<div class="form-group row justify-content-md-center">
    <div class="col-md-auto">
        <div class="input-group mb-2">
            <?php echo $this->formText($form->get('playDate')->setFormat('d-m-Y')); ?>
            <div class="input-group-prepend">
                <div class="input-group-text" style="border-radius: 0 .25rem .25rem 0;"><i class="fas fa-calendar-alt"></i></div>
            </div>
        </div>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="submit" id="submit" class="btn btn-dark"><?php echo $this->translator()->translate('save') ?></button> 
        <a href="<?php echo $this->url['games']; ?>" class="btn btn-danger" title="<?php echo $this->translator()->translate('cancel') ?>"><?php echo $this->translator()->translate('cancel') ?></a>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>
<?php
$unixStartTime = strtotime($season->getStartDate()->format('Y-m-d'));
$unixEndTime = strtotime($season->getEndDate()->format('Y-m-d'));
?>
<script>
  $( function() {
    $( ".datepicker" ).datepicker({ 
        minDate: new Date(<?php echo $unixStartTime; ?> * 1000), 
        maxDate: new Date(<?php echo $unixEndTime; ?> * 1000),
        dateFormat: 'dd-mm-yy',
        showWeek: true,
        setDate: new Date(<?php echo $unixStartTime; ?> * 1000)
        });
  } );
  </script>