<?php
$this->headTitle($this->translator()->translate('player.title'));

$this->mainMenu()->setActiveItemId('player');

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('player.manage') => $this->url('players'),
]);
?>
<div class="row">
    <h1 class="col"><?php echo $this->translator()->translate('player.manage') ?></h1>
</div>
<div class="row">
    <div class="col">
        <a class="btn btn-dark" href="
           <?= $this->url('players', ['action' => 'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translator()->translate('player.new') ?>
        </a>
    </div>
    <div class="col text-right">
        <form class="form-inline" name="searchCustomer" method="post" action="<?php echo $this->url('players'); ?>">
            <div class="col text-right" style="padding-right:0;">
                <input class="form-control" name="search" value="<?php echo $searchString; ?>" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-dark" type="submit">Search</button>
            </div>
        </form>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        <table class="table table-striped table-condensed">
            <thead class="thead-dark">
                <tr>
                    <th><?php echo $this->translator()->translate('player.sur.name') ?></th>
                    <th><?php echo $this->translator()->translate('player.last.name') ?></th>
                    <th><?php echo $this->translator()->translate('player.date.created') ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <?php if (count($players) > 0) { ?>
            <?php foreach ($players as $player): ?>
                <tr>
                    <td>
                        <?= $this->escapeHtml($player->getSurName()); ?></a> 
                    </td>
                    <td>
                        <?= $this->escapeHtml($player->getLastName()) . ($player->getLastNamePrefix()? ', ' . $player->getLastNamePrefix(): ''); ?></a> 
                    </td>
                    <td>
                        <?= (is_object($player->getCreatedAt()) ? $this->escapeHtml($player->getCreatedAt()->format('Y-m-d H:m')) : ''); ?>
                    </td>        
                    <td>
                        <a class="btn btn-dark btn-sm" href="<?= $this->url('players', ['action' => 'edit', 'id' => $player->getId()]); ?>">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-dark btn-sm" href="<?= $this->url('players', ['action' => 'show', 'id' => $player->getId()]); ?>">
                            <i class="fas fa-search-plus"></i>
                        </a>
                        <a class="btn btn-danger btn-sm" href="<?= $this->url('players', ['action' => 'delete', 'id' => $player->getId()]); ?>">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>    
                </tr>
            <?php endforeach; ?>  
            <?php } else { ?>
                <tr>
                    <td colspan="5" class="text-center"><?php echo $this->translator()->translate('no.players.found') ?></td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>
