<?php
$this->headTitle($this->translator()->translate('competition.title'));

$this->mainMenu()->setActiveItemId('competition');

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('competition.manage') => $this->url('competitions'),
    $this->translator()->translate('competition.add') => $this->url('competitions', ['action' => 'add'])
]);
$form->setAttributes(array(
    'enctype' => 'multipart/form-data'
));
?>
<h1><?php echo $this->translator()->translate('competition.manage') ?></h1>
<?php
echo $this->partial('competition/competition/partials/form.phtml', array('form' => $form));
?>