<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Fifa Reports Competition')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/rp-logo.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/datatables/DataTables-1.10.18/dataTables.bootstrap4.min.css'))
            ->prependStylesheet($this->basePath('css/jquery-ui-1.12.1/jquery-ui.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-4.0.0/bootstrap.min.css'))
        ?>
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css?family=Khand" rel="stylesheet">
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootbox/bootbox.min.js'))
            ->prependFile($this->basePath('js/bootstrap-4.0.0/bootstrap.bundle.js'))
            ->prependFile($this->basePath('js/datatables/DataTables-1.10.18/dataTables.bootstrap4.min.js'))
            ->prependFile($this->basePath('js/datatables/datatables.min.js'))
            ->prependFile($this->basePath('js/jquery-ui-1.12.1/jquery-ui.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <!-- Page header -->
                <div class="col-md-4">
                    <div class="app-caption">
                        <img src="<?php echo $this->basePath() . '/img/logoreports.svg'; ?>" width="300" height="auto" alt="Fifa Reports" />
                    </div>
                </div>                
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->
                    <?php
                    // Check if the activeMenuItemId passed to layout view model
                    // and if so, use it for setting active navbar item.
                    if (isset($activeMenuItemId)) {
                        $this->mainMenu()->setActiveItemId($activeMenuItemId);
                    }

                    // Render the navbar
                    echo $this->mainMenu()->render();
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?= $this->pageBreadcrumbs()->render(); ?>
                </div>
            </div>
            <?php
            $flashMessenger = $this->flashMessenger()
                ->setMessageOpenFormat(
                    '<div%s>
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">
						&times;
					</button>
				<ul class="flashMessages"><li>')
                ->setMessageSeparatorString('</li><li>')
                ->setMessageCloseString('</li></ul></div>');
            ?>
            <?php
            echo $this->flashMessenger()->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
            echo $this->flashMessenger()->render('info', array('alert', 'alert-dismissable', 'alert-info'));
            echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
            echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success'));
            ?>



            <div class="row">
                <div class="col-md-12">
                    <!-- Page content placeholder -->
                    <?= $this->content; ?>
                </div>
            </div>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Reports. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
