<div class="form-group row">
    <?php echo $this->formLabel($form->get('name')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formText($form->get('name')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('name')); ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('city')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formText($form->get('city')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('city')); ?>
    </div>
</div>