<?php echo $this->form()->openTag($form); ?>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('name')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <?php echo $this->formText($form->get('name')); ?>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('name')); ?>
    </div>
</div>
<div class="form-group row">
    <?php echo $this->formLabel($form->get('awayHomeGame')); ?>
    <div class="col-lg-6 col-md-6 col-sm-6">
        <label class="switch">
            <?php echo $this->formCheckbox($form->get('awayHomeGame')); ?>
            <span class="slider round"></span>
        </label>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2">
        <?php echo $this->formElementErrors($form->get('awayHomeGame')); ?>
    </div>
</div>
<div class="form-group row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="submit" id="submit" class="btn btn-dark"><?php echo $this->translator()->translate('save') ?></button> 
        <a href="<?php echo $this->url('competitions'); ?>" class="btn btn-danger" title="<?php echo $this->translator()->translate('cancel') ?>"><?php echo $this->translator()->translate('cancel') ?></a>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>