<?php
$this->headTitle($this->translator()->translate('club.title'));

$this->mainMenu()->setActiveItemId('club');

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('club.manage') => $this->url('clubs'),
    $this->translator()->translate('club.edit') => $this->url('clubs', ['action' => 'edit'])
]);
$form->setAttributes(array(
    'enctype' => 'multipart/form-data'
));
?>
<h1><?php echo $this->translator()->translate('club.manage') ?></h1>
<?php echo $this->form()->openTag($form); ?>
<?php
echo $this->partial('club/club/partials/form.phtml', array('form' => $form));
?>
<!-- Image upload -->
<?php echo $this->partial('club/club/partials/show_image.phtml', array('formImage' => $formImage, 'image' => $image)); ?>
<!-- End image upload -->
<div class="form-group row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <button type="submit" id="submit" class="btn btn-dark"><?php echo $this->translator()->translate('save') ?></button>
        <a href="<?php echo $this->url['clubs']; ?>" class="btn btn-danger" title="<?php echo $this->translator()->translate('cancel') ?>"><?php echo $this->translator()->translate('cancel') ?></a>
    </div>
</div>
<?php echo $this->form()->closeTag($form); ?>
