<?php
$this->headTitle($this->translator()->translate('clubs.title'));

$this->mainMenu()->setActiveItemId('club');

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('manage.clubs') => $this->url('clubs'),
]);
?>
<div class="row">
    <h1 class="col"><?php echo $this->translator()->translate('manage.clubs') ?></h1>
</div>
<div class="row">
    <div class="col">
        <a class="btn btn-dark" href="
           <?= $this->url('clubs', ['action' => 'add']); ?>">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <?php echo $this->translator()->translate('new.club') ?>
        </a>
    </div>
    <div class="col text-right">
        <form class="form-inline" name="searchClub" method="post" action="<?php echo $this->url('clubs'); ?>">
            <div class="col text-right" style="padding-right:0;">
                <input class="form-control" name="search" value="<?php echo $searchString; ?>" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-dark" type="submit">Search</button>
            </div>
        </form>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        <table class="table table-striped table-condensed">
            <thead class="thead-dark">
                <tr>
                    <th><?php echo $this->translator()->translate('club.name') ?></th>
                    <th><?php echo $this->translator()->translate('club.date.created') ?></th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <?php if (count($clubs) > 0) { ?>
            <?php foreach ($clubs as $club): ?>
                <tr>
                    <td>
                        <?= $this->escapeHtml($club->getName()); ?></a> 
                    </td>
                    <td>
                        <?= (is_object($club->getCreatedAt()) ? $this->escapeHtml($club->getCreatedAt()->format('Y-m-d H:m')) : ''); ?>
                    </td>        
                    <td>
                        <a class="btn btn-dark btn-sm" href="<?= $this->url('clubs', ['action' => 'edit', 'id' => $club->getId()]); ?>">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-danger btn-sm" href="<?= $this->url('clubs', ['action' => 'delete', 'id' => $club->getId()]); ?>">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>    
                </tr>
            <?php endforeach; ?>  
            <?php } else { ?>
                <tr>
                    <td colspan="5" class="text-center"><?php echo $this->translator()->translate('no.clubs.found') ?></td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>
