<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
    'Home' => $this->url('home')
]);
?>
<div class="row mb-2" id="carousel">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="https://apollo2.dl.playstation.net/cdn/EP0006/CUSA11608_00/FREE_CONTENTQBDo6Zwy82aZ3zpecu0i/FIFA19_06.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://gamemania-sec.azureedge.net/-/media/Sites/GameMania/Products/Games/F/FIFA/FIFA-19/Screenshots/FIFA-19-02.jpg?v=RkwW7wc2OUaHHKCiUwdrUA&Type=Small" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="https://data4.origin.com/content/dam/originx/web/app/games/fifa/fifa-19/screenshots/FIFA19_gdp_screenshot_RamonSanchezPizjuan.jpg" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<div class="mb-4" id="nextMatch">
    <div class="row mb-2">
        <h2 class="col text-center">Wedstrijden week <?php echo $weekNr; ?></h2>
    </div>
<?php foreach ($games as $game){ ?>
    <div class="row mb-2">
        <div class="col text-right">
            <?php echo $game->getHomePlayer()->getFullNameShortLastName(); ?>
        </div>
        <div class="col-md-2 text-center">
            <i class="far fa-futbol"></i>
        </div>
        <div class="col">
            <?php echo $game->getAwayPlayer()->getFullNameShortLastName(); ?>
        </div>
    </div>   
<?php } ?>
</div>
<div class="row mb-2">
    <h2 class="col text-center"><?php echo $season->getName(); ?></h2>
</div>
<div class="row mb-2" id="game">
    <?php foreach ($season->getCompetitions() as $competition) { ?>

        <div class="col">
            <div class="card">
                <div class="card-header text-white bg-dark">
                    <b><?php echo $competition->getName(); ?></b>
                </div>
                    
                <div class="card-body">
                    <table class="table table-bordered table-hover table-sm">
                        <tr>
                            <th class="text-center">Player</th>
                            <th class="text-center">G <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="right" title="Gespeeld"></i></th>
                            <th class="text-center">P <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="right" title="Punten"></i></th>
                            <th class="text-center">W <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="right" title="Winst"></i></th>
                            <th class="text-center">G <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="right" title="Gelijk"></i></th>
                            <th class="text-center">V <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="right" title="Verloren"></i></th>
                            <th class="text-center">DS <i class="fas fa-info-circle" data-toggle="tooltip" data-placement="right" title="Doelsaldo"></i></th>
                        </tr>
                        <?php foreach ($competition->getPlayers() as $player) { ?>
                            <tr>
                                <td>
                                    <?php echo $player->getSurName(); ?>
                                </td>
                                <td>0</td>
                                <td>0</td>
                                <td>0</td>
                                <td>0</td>
                                <td>0</td>
                                <td>0</td>
                            </tr>
                        <?php } ?>
                    </table>
                </div>
            </div>
        </div>

    <?php } ?>

</div>



