<?php
$this->headTitle($this->translator()->translate('player.profile'));

$this->mainMenu()->setActiveItemId('profile');

$this->pageBreadcrumbs()->setItems([
    $this->translator()->translate('home') => $this->url('home'),
    $this->translator()->translate('player.profile') => $this->url('application', ['action' => 'profile']),
]);
?>

<div class="row mt-3">
    <h2 class="col"><?php echo $this->translator()->translate('player.profile'); ?></h2>
</div>
<div class="row">
    <div class="col-md-auto">
        <?php
        $image = (is_object($player->getPlayerImage()) ? $player->getPlayerImage() : null);
        if (is_object($image)) {
            echo '<img class="img-thumbnail img-responsive " src="/' . $player->getPlayerImage()->getImageTypes('400x400')[0]->getFolder() . $player->getPlayerImage()->getImageTypes('400x400')[0]->getFileName() . '?v=' . rand() . '" alt="' . $player->getPlayerImage()->getAlt() . '"/>';
        } else {
        ?>
        <img class="img-thumbnail img-responsive " src="/img/no-profile-img.jpg" alt="<?php echo $this->translator()->translate('player.no.profile.img'); ?>" width="400" height="400" />

        <?php } ?>
    </div>
    <div class="col">
        <?php echo $player->getFullName(); ?><br/>
        <?php echo $player->getScreenName(); ?><br/>
        <?php echo(is_object($player->getClub()) ? $player->getClub()->getName() : ''); ?>
    </div>
</div>
<div class="row mt-3">
    <div class="col">
        <table id="gamesTable" class="table table-bordered table-hover table-sm">
            <thead class="thead-dark">
            <tr>
                <th class="text-center">#</th>
                <th class="text-center">#</th>
                <th colspan="5"><?php echo $this->translator()->translate('competition.game.players'); ?></th>
                <th class="text-center"><?php echo $this->translator()->translate('competition.game.date'); ?></th>
            <tr>
            </thead>
            <tbody>
            <?php if (count($player->getAllGames()) > 0) { ?>
                <?php foreach ($player->getAllGames() as $index => $game) { ?>
                    <tr>
                        <td class="text-center"><?php echo $index + 1; ?></td>
                        <td class="text-center"><?php echo $game->getSortOrder(); ?></td>
                        <td class="border-right-0"><?php echo $game->getHomePlayer()->getFullName() ?></td>
                        <td class="text-center border-right-0"><?php echo(is_object($game->getHomeResult()) ? $game->getHomeResult()->getGoals() : ''); ?></td>
                        <td class="text-center border-right-0 border-left-0">-</td>
                        <td class="text-center border-left-0"><?php echo(is_object($game->getAwayResult()) ? $game->getAwayResult()->getGoals() : ''); ?></td>
                        <td class="text-right border-left-0"><?php echo $game->getAwayPlayer()->getFullName(); ?></td>
                        <td class="text-center"><?php echo(is_object($game->getPlayDate()) ? $game->getPlayDate()->format('d-m-Y') : ''); ?></td>
                    </tr>
                <?php } ?>
            <?php } else { ?>
                <tr id="noGenerateGames">
                    <td colspan="5"
                        class="text-center"><?php echo $this->translator()->translate('competition.no.games'); ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>

</div>

