<?php
$this->headTitle('Rules');

$this->mainMenu()->setActiveItemId('rules');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Rules'=>$this->url('rules'),
            ]);
?>

<h1>Rules</h1>

<p>
    De volgende '<i>regels</i>' zijn van toepassing op de Fifa Reports competitie.
</p>
<h4>Eerste ronde, Groepsfase</h4>
<p>
De eerste ronde van het toernooi wordt gespeeld in vier groepen van vijf clubs. De indeling van deze groepen wordt bepaald door een "geleide" loting, die met behulp van coëfficiënten zou moeten resulteren in groepen die ongeveer gelijk van sterkte zijn.
<br/><br/>
De nummers één tot en met vier van iedere poule gaan door naar de tweede ronde.. Voor de nummer vijf van de groep is het FIFA reports toernooi voor het betreffende seizoen voorbij. Indien meerdere clubs hetzelfde aantal punten halen, wordt gekeken naar het onderlinge resultaat.
</p>
<h4>Tweede ronde, knock-outfase</h4>
<p>
    De tweede ronde bestaat uit knock-outwedstrijden met alleen &eacute;&eacute;n wedstrijd (thuis/uit) in plaats van een thuis- en uitwedstrijd.
    De knock-out bestaat uit elke keer 1 wedstrijd. Bij een gelijke stand na de reguliere speeltijd wordt er verlening gespeeld. 
    Is het na de verlenging nog steeds gelijk dan moeten strafschoppen tot een winaar leiden.
</p>
<h4>Finale</h4>
<p>
    De finale bestaat uit 1 wedstrijd. Bij een gelijke stand na de reguliere speeltijd wordt er verlening gespeeld. 
    Is het na de verlenging nog steeds gelijk dan moeten strafschoppen tot een winaar leiden. De winnaar van de finale mag zich een jaar lang de Fifa Reports kampioen noemen.
</p>

<h2>Wedstrijden</h2>
<h4>Wedstrijd spelen</h4>
<p>
    Per week wordt er per groep een wedstrijd gespeeld. Dat betekent dat er per week 4 wedstrijden worden gespeeld. De data voor de wedstrijden is een leidraad. Mocht je die week niet kunnen, verplaats dan even met je tegenstander
    de wedstrijd naar een tijdstip dat jullie wel kunnen. Waarbij we graag willen dat je de wedstrijd tijdens de lunch speelt (wat ook leuk is omdat er dan publiek is) of na werktijd (17:00).
</p>
<p>
    Wat leuk is dat na de wedstrijd er een foto gemaakt wordt van de statistieken. Zodat ik dit kan invoeren in het systeem.<br/><br/>
    <img src="img/voorbeeld-statistieken.jpg" alt="Voorbeeld foto statistieken" width="500" height="auto" />
</p>

<h4>Teams</h4>
<p>
    Bij het spelen van een wedstrijd mag er voor elke team gekozen worden. Dit mag zowel een club uit een specifieke competitie zijn (Bijvoorbeeld Barcelona).
    Maar ook een internationaal team mag gekozen worden (Bijvoorbeeld: Frankrijk, Nederland etc.).

    Op volgende link kan je de sterkte van teams bekijken in volgorde van hoog naar laag: <a href="https://www.fifaindex.com/nl/teams/" title="fifa index">fifa index</a>.

</p>
<p>
    
</p>
